---

# Main tasks file for jupyterhub role

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::jupyterhub'
    - 'role::jupyterhub::init'
